databases:
  - name: mysitedb
    plan: free
    databaseName: DB_NAME
    user: DB_USER

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"